[package]
name = "mlrs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
criterion = "0.8"

[[bench]]
name = "matmul"
harness = false

[[bench]]
name = "elementwise"
harness=false

[[bench]]
name = "autograd"
harness=false
